### ISSUE TITLE
Identify events in soccer that we can detect in video

### ISSUE THREAD

**Issue by Bo887** [CS196Illinois/Event_Detection#5]
Identify all possible events in soccer that we can detect in video.
@sathp

**Comment by FSSoar** [comment]
- Scoring a goal
- Passing
- Intercepting 
- Yellow Card
- Red Card 
- Corner Kicks
- Blocking a goal
- “Kickoff” (start of the game)
- Offsides
- Penalty Kicks
- Shootout
- Injury
